site_name: Advanced Higher CS

theme:
    name: readthedocs

navigation_depth: 4

nav:
    - Home: index.md
    - SDD:
        - Software: sdd/AH-CS-SDD.md
        - OOP: sdd/AH-CS-SDD-OOP.md
        - Standard algorithms: sdd/AH-CS-SDD-Standard-Algorithms.md
        - 2D Array: sdd/AH-CS-SDD-2D-Array.md
        - Linked List: sdd/AH-CS-SDD-Linked-List.md
    - DDD: ddd/AH-CS-DDD.md
    - Integration: integration/AH-CS-Integration.md
    - WDD: wdd/AH-CS-WDD.md
